### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by gajop** [dansan/infolog-upload#18]
http://logs.springrts.com/ gives me 503

**Comment by dansan** [comment]
CC: @abma
Strange… I see gunicorn processes running on the server for `springrts_logs.wsgi`, `runserver_jsonrpc_over_tcp` and systemd seems happy (`springrts-logs-gunicorn.service`, `springrts-logs-gunicorn.socket`, `springrts-logs_via_tcp.service`).
But they haven't logged anything since `Dec 24`.
I have restarted all services and they are again running happily, but are still inaccessible.
Aha… seems the `springrts-logs-gunicorn.socket` service must be started last or it won't create the unix socket (`/run/gunicorn/infolog.socket`) for apache to connect to.
Bad luck I guess… hope it doesn't happen again.
